---

- name: openssl | creating keys directory
  sudo: yes
  file:
    path:  "{{ item.key_path  | default(openssl_keys_path) }}"
    owner: "{{ item.owner     | default('root') }}"
    group: "{{ item.group     | default('root') }}"
    state: directory
    mode:  0700
  with_items: openssl_certificates
  tags:
    - system
    - openssl
    - create

- name: openssl | creating certs directory
  sudo: yes
  file:
    path:  "{{ item.cert_path  | default(openssl_certs_path) }}"
    owner: "{{ item.owner      | default('root') }}"
    group: "{{ item.group      | default('root') }}"
    state: directory
    mode:  0755
  with_items: openssl_certificates
  tags:
    - system
    - openssl
    - create

